### ISSUE TITLE
Need special josn processor for elasticsearch

### ISSUE THREAD

**Issue by datafibers** [datafibers/df_demo#1]
It is known the KAFKA connect use special JSON format. As result, we need to support to create such format for demo purpose. There are following changes needed.
- [ ] df-reactive-agent: need to support FILTER_TYPE = KAFKA_CONNECT_JSON in HTTP header to indicate such special handling
- [ ] df-reactive-server: need to add new features (in class MsgFilter) to convert regular JSON string to "{\"attribute\":\"value\"}". In addition, we need additional \ ahead of \ in data.

**Comment by SchubertZhu** [comment]
I am working these changes, and they will be available in GitHub soon.

I will keep the team posted.

Regards,

Schubert

**Comment by datafibers** [comment]
fixed by [SchubertZhu](https://github.com/SchubertZhu)
